version: '2'
services:
  workspace:
    build: ./docker/workspace
    container_name: workspace
    volumes:
      - .:/app
    command: sh -c 'cd /app && composer install'
  app:
    image: php:7.0.15-alpine
    container_name: app
    ports:
      - 80:80
    volumes_from:
      - workspace
    command: sh -c 'cd /app && php artisan serve --host=0.0.0.0 --port=80'
